"""date column add

Revision ID: 431f9d3b05fb
Revises: 4e82618631a2
Create Date: 2025-03-13 13:33:43.421738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '431f9d3b05fb'
down_revision: Union[str, None] = '4e82618631a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_churches', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tb_churches', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tb_church_admins', sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('now()')))
    op.add_column('tb_church_admins', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tb_church_admins', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    op.add_column('tb_bulletin_templates', sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False))
    op.add_column('tb_bulletin_templates', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    op.add_column('tb_bulletins', sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False))
    op.add_column('tb_bulletins', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    op.execute("UPDATE tb_churches SET is_deleted = FALSE")
    op.execute("UPDATE tb_church_admins SET is_deleted = FALSE")
    op.execute("UPDATE tb_bulletin_templates SET is_deleted = FALSE")

    op.alter_column('tb_churches', 'is_deleted', nullable=False)
    op.alter_column('tb_church_admins', 'is_deleted', nullable=False)
    op.alter_column('tb_bulletin_templates', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_bulletins', 'deleted_at')
    op.drop_column('tb_bulletins', 'is_deleted')
    op.drop_column('tb_bulletin_templates', 'deleted_at')
    op.drop_column('tb_bulletin_templates', 'is_deleted')
    op.drop_column('tb_church_admins', 'updated_at')
    op.drop_column('tb_church_admins', 'deleted_at')
    op.drop_column('tb_church_admins', 'is_deleted')
    op.drop_column('tb_churches', 'deleted_at')
    op.drop_column('tb_churches', 'is_deleted')
    # ### end Alembic commands ###
