"""index change

Revision ID: 594b635e7881
Revises: be0f11e70ec5
Create Date: 2025-03-18 09:23:19.622018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '594b635e7881'
down_revision: Union[str, None] = 'be0f11e70ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tb_bulletin_templates', 'id',
        existing_type=sa.INTEGER(),
        comment='주보 템플릿 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_bulletin_templates'::regclass)")
    )
    op.alter_column(
        'tb_bulletin_templates', 'church_id',
        existing_type=sa.INTEGER(),
        comment='교회 ID',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletin_templates', 'name',
        existing_type=sa.VARCHAR(),
        comment='템플릿 이름',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletin_templates', 'template_data',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment='기본 템플릿 데이터',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletin_templates', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_bulletin_templates', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='수정일시',
        existing_nullable=True
    )
    op.alter_column(
        'tb_bulletin_templates', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_bulletin_templates', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='삭제일시',
        existing_nullable=True
    )
    op.alter_column(
        'tb_bulletins', 'id',
        existing_type=sa.INTEGER(),
        comment='주보 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_bulletins'::regclass)")
    )
    op.alter_column(
        'tb_bulletins', 'church_id',
        existing_type=sa.INTEGER(),
        comment='교회 ID',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletins', 'template_id',
        existing_type=sa.INTEGER(),
        nullable=True,
        comment='템플릿 ID'
    )
    op.alter_column(
        'tb_bulletins', 'date',
        existing_type=sa.DATE(),
        comment='주보 날짜',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletins', 'content',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment='실제 주보 내용',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletins', 'is_published',
        existing_type=sa.CHAR(length=1),
        comment='게시 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_bulletins', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_bulletins', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='수정일시',
        existing_nullable=True
    )
    op.alter_column(
        'tb_bulletins', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_bulletins', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='삭제일시',
        existing_nullable=True
    )

    op.alter_column(
        'tb_church_admins', 'id',
        existing_type=sa.INTEGER(),
        comment='교회 관리자 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_church_admins'::regclass)")
    )
    op.alter_column(
        'tb_church_admins', 'church_id',
        existing_type=sa.INTEGER(),
        comment='교회 ID',
        existing_nullable=False
    )
    op.alter_column(
        'tb_church_admins', 'user_id',
        existing_type=sa.INTEGER(),
        comment='사용자 ID',
        existing_nullable=False
    )
    op.alter_column(
        'tb_church_admins', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_church_admins', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='수정일시',
        existing_nullable=True
    )
    op.alter_column(
        'tb_church_admins', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_church_admins', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='삭제일시',
        existing_nullable=True
    )

    op.alter_column(
        'tb_churches', 'id',
        existing_type=sa.INTEGER(),
        comment='교회 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_churches'::regclass)")
    )
    op.alter_column(
        'tb_churches', 'church_code',
        existing_type=sa.VARCHAR(),
        comment='교회 코드',
        existing_nullable=False
    )
    op.alter_column(
        'tb_churches', 'name',
        existing_type=sa.VARCHAR(),
        comment='교회 이름',
        existing_nullable=False
    )
    op.alter_column(
        'tb_churches', 'address',
        existing_type=sa.VARCHAR(),
        comment='교회 주소',
        existing_nullable=True
    )
    op.alter_column(
        'tb_churches', 'contact_info',
        existing_type=sa.VARCHAR(),
        comment='교회 연락처',
        existing_nullable=True
    )
    op.alter_column(
        'tb_churches', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()'))
    op.alter_column(
        'tb_churches', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='수정일시',
        existing_nullable=True
    )
    op.alter_column(
        'tb_churches', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_churches', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='삭제일시',
        existing_nullable=True
    )

    op.alter_column(
        'tb_users', 'id',
        existing_type=sa.INTEGER(),
        comment='사용자 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_users'::regclass)")
    )
    op.alter_column(
        'tb_users', 'email',
        existing_type=sa.VARCHAR(),
        comment='이메일',
        existing_nullable=False
    )
    op.alter_column(
        'tb_users', 'hashed_password',
        existing_type=sa.VARCHAR(),
        comment='비밀번호',
        existing_nullable=False
    )
    op.alter_column(
        'tb_users', 'full_name',
        existing_type=sa.VARCHAR(),
        comment='이름',
        existing_nullable=True
    )
    op.alter_column(
        'tb_users', 'is_active',
        existing_type=sa.BOOLEAN(),
        comment='활성화 여부',
        existing_nullable=True,
        existing_server_default=sa.text('true')
    )
    op.alter_column(
        'tb_users', 'is_superuser',
        existing_type=sa.BOOLEAN(),
        comment='슈퍼유저 여부',
        existing_nullable=True,
        existing_server_default=sa.text('false')
    )
    op.alter_column(
        'tb_users', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_users', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='수정일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_users', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_users', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment='삭제일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )

    op.drop_constraint('tb_bulletin_templates_church_id_fkey', 'tb_bulletin_templates', type_='foreignkey')
    op.drop_constraint('tb_bulletins_church_id_fkey', 'tb_bulletins', type_='foreignkey')
    op.drop_constraint('tb_bulletins_template_id_fkey', 'tb_bulletins', type_='foreignkey')
    op.drop_constraint('tb_church_admins_church_id_fkey', 'tb_church_admins', type_='foreignkey')
    op.drop_constraint('tb_church_admins_user_id_fkey', 'tb_church_admins', type_='foreignkey')

    op.drop_constraint('tb_bulletin_templates_pkey', 'tb_bulletin_templates', type_='primary')
    op.drop_constraint('tb_bulletins_pkey', 'tb_bulletins', type_='primary')
    op.drop_constraint('tb_church_admins_pkey', 'tb_church_admins', type_='primary')
    op.drop_constraint('tb_churches_pkey', 'tb_churches', type_='primary')
    op.drop_constraint('tb_users_pkey', 'tb_users', type_='primary')

    op.create_primary_key('pk_users', 'tb_users', ['id'])
    op.create_primary_key('pk_churches', 'tb_churches', ['id'])
    op.create_primary_key('pk_church_admins', 'tb_church_admins', ['id'])
    op.create_primary_key('pk_bulletins', 'tb_bulletins', ['id'])
    op.create_primary_key('pk_bulletin_templates', 'tb_bulletin_templates', ['id'])

    op.create_foreign_key('fk_church_admins__user_id', 'tb_church_admins', 'tb_users', ['user_id'], ['id'], onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key('fk_church_admins__church_id', 'tb_church_admins', 'tb_churches', ['church_id'], ['id'], onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key('fk_bulletins__template_id', 'tb_bulletins', 'tb_bulletin_templates', ['template_id'], ['id'], onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key('fk_bulletins__church_id', 'tb_bulletins', 'tb_churches', ['church_id'], ['id'], onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key('fk_bulletin_templates__church_id', 'tb_bulletin_templates', 'tb_churches', ['church_id'], ['id'], onupdate='NO ACTION', ondelete='NO ACTION')

    op.drop_index('ix_bulletin_templates__id', table_name='tb_bulletin_templates')
    op.drop_index('ix_bulletins__id', table_name='tb_bulletins')
    op.drop_index('ix_church_admins__id', table_name='tb_church_admins')
    op.drop_index('ix_churches__church_code', table_name='tb_churches')
    op.drop_index('ix_churches__id', table_name='tb_churches')
    op.create_unique_constraint('uq_churches__church_code', 'tb_churches', ['church_code'])
    op.drop_index('ix_users__email', table_name='tb_users')
    op.drop_index('ix_users__id', table_name='tb_users')
    op.drop_constraint('tb_users_email_key', 'tb_users', type_='unique')
    op.create_unique_constraint('uq_users__email', 'tb_users', ['email'])

    op.create_index('ix_bulletin_templates__church_id', 'tb_bulletin_templates', ['church_id'])
    op.create_index('ix_bulletins__church_id', 'tb_bulletins', ['church_id'])
    op.create_index('ix_bulletins__template_id', 'tb_bulletins', ['template_id'])
    op.create_index('ix_church_admins__church_id', 'tb_church_admins', ['church_id'])
    op.create_index('ix_church_admins__user_id', 'tb_church_admins', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_church_admins__church_id', 'tb_church_admins', type_='foreignkey')
    op.drop_constraint('fk_church_admins__user_id', 'tb_church_admins', type_='foreignkey')
    op.drop_constraint('fk_bulletins__church_id', 'tb_bulletins', type_='foreignkey')
    op.drop_constraint('fk_bulletins__template_id', 'tb_bulletins', type_='foreignkey')
    op.drop_constraint('fk_bulletin_templates__church_id', 'tb_bulletin_templates', type_='foreignkey')

    op.drop_constraint('pk_users', 'tb_users', type_='primary')
    op.drop_constraint('pk_churches', 'tb_churches', type_='primary')
    op.drop_constraint('pk_church_admins', 'tb_church_admins', type_='primary')
    op.drop_constraint('pk_bulletins', 'tb_bulletins', type_='primary')
    op.drop_constraint('pk_bulletin_templates', 'tb_bulletin_templates', type_='primary')

    op.create_primary_key('tb_bulletin_templates_pkey', 'tb_bulletin_templates', ['id'])
    op.create_primary_key('tb_bulletins_pkey', 'tb_bulletins', ['id'])
    op.create_primary_key('tb_church_admins_pkey', 'tb_church_admins', ['id'])
    op.create_primary_key('tb_churches_pkey', 'tb_churches', ['id'])
    op.create_primary_key('tb_users_pkey', 'tb_users', ['id'])

    op.create_foreign_key('tb_church_admins_user_id_fkey', 'tb_church_admins', 'tb_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tb_church_admins_church_id_fkey', 'tb_church_admins', 'tb_churches', ['church_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tb_bulletins_template_id_fkey', 'tb_bulletins', 'tb_bulletin_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tb_bulletins_church_id_fkey', 'tb_bulletins', 'tb_churches', ['church_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tb_bulletin_templates_church_id_fkey', 'tb_bulletin_templates', 'tb_churches', ['church_id'], ['id'], ondelete='CASCADE')

    op.drop_index('ix_bulletin_templates__church_id', 'tb_bulletin_templates')
    op.drop_index('ix_bulletins__church_id', 'tb_bulletins')
    op.drop_index('ix_bulletins__template_id', 'tb_bulletins')
    op.drop_index('ix_church_admins__church_id', 'tb_church_admins')
    op.drop_index('ix_church_admins__user_id', 'tb_church_admins')

    op.drop_constraint('uq_users__email', 'tb_users', type_='unique')
    op.create_unique_constraint('tb_users_email_key', 'tb_users', ['email'])
    op.create_index('ix_users__id', 'tb_users', ['id'], unique=False)
    op.create_index('ix_users__email', 'tb_users', ['email'], unique=False)
    op.drop_constraint('uq_churches__church_code', 'tb_churches', type_='unique')
    op.create_index('ix_churches__id', 'tb_churches', ['id'], unique=False)
    op.create_index('ix_churches__church_code', 'tb_churches', ['church_code'], unique=True)
    op.create_index('ix_church_admins__id', 'tb_church_admins', ['id'], unique=False)
    op.create_index('ix_bulletins__id', 'tb_bulletins', ['id'], unique=False)
    op.create_index('ix_bulletin_templates__id', 'tb_bulletin_templates', ['id'], unique=False)

    op.alter_column(
        'tb_users', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='삭제일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_users', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment=None,
        existing_comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_users', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='수정일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_users', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_users', 'is_superuser',
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment='슈퍼유저 여부',
        existing_nullable=True,
        existing_server_default=sa.text('false')
    )
    op.alter_column(
        'tb_users', 'is_active',
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment='활성화 여부',
        existing_nullable=True,
        existing_server_default=sa.text('true')
    )
    op.alter_column(
        'tb_users', 'full_name',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='이름',
        existing_nullable=True
    )
    op.alter_column(
        'tb_users', 'hashed_password',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='비밀번호',
        existing_nullable=False
    )
    op.alter_column(
        'tb_users', 'email',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='이메일',
        existing_nullable=False
    )
    op.alter_column(
        'tb_users', 'id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='사용자 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_users'::regclass)")
    )

    op.alter_column(
        'tb_churches', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='삭제일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_churches', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment=None,
        existing_comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_churches', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='수정일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_churches', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_churches', 'contact_info',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='교회 연락처',
        existing_nullable=True
    )
    op.alter_column(
        'tb_churches', 'address',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='교회 주소',
        existing_nullable=True
    )
    op.alter_column(
        'tb_churches', 'name',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='교회 이름',
        existing_nullable=False
    )
    op.alter_column(
        'tb_churches', 'church_code',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='교회 코드',
        existing_nullable=False
    )
    op.alter_column(
        'tb_churches', 'id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='교회 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_churches'::regclass)")
    )

    op.alter_column(
        'tb_church_admins', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='삭제일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_church_admins', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment=None,
        existing_comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_church_admins', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='수정일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_church_admins', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_church_admins', 'user_id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='사용자 ID',
        existing_nullable=False
    )
    op.alter_column(
        'tb_church_admins', 'church_id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='교회 ID',
        existing_nullable=False
    )
    op.alter_column(
        'tb_church_admins', 'id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='교회 관리자 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_church_admins'::regclass)")
    )

    op.alter_column(
        'tb_bulletins', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='삭제일시',
        existing_nullable=True
    )
    op.alter_column(
        'tb_bulletins', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment=None,
        existing_comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_bulletins', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='수정일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_bulletins', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_bulletins', 'is_published',
        existing_type=sa.CHAR(length=1),
        comment=None,
        existing_comment='게시 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_bulletins', 'content',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment='실제 주보 내용',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletins', 'date',
        existing_type=sa.DATE(),
        comment=None,
        existing_comment='주보 날짜',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletins', 'template_id',
        existing_type=sa.INTEGER(),
        nullable=False,
        comment=None,
        existing_comment='템플릿 ID'
    )
    op.alter_column(
        'tb_bulletins', 'church_id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='교회 ID',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletins', 'id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='주보 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_bulletins'::regclass)")
    )

    op.alter_column(
        'tb_bulletin_templates', 'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='삭제일시', existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_bulletin_templates', 'is_deleted',
        existing_type=sa.CHAR(length=1),
        comment=None,
        existing_comment='삭제 여부',
        existing_nullable=False,
        existing_server_default=sa.text("'F'::bpchar")
    )
    op.alter_column(
        'tb_bulletin_templates', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='수정일시',
        existing_nullable=True
    )
    op.alter_column(
        'tb_bulletin_templates', 'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment='생성일시',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.alter_column(
        'tb_bulletin_templates', 'template_data',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment='기본 템플릿 데이터',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletin_templates', 'name',
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment='템플릿 이름',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletin_templates', 'church_id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='교회 ID',
        existing_nullable=False
    )
    op.alter_column(
        'tb_bulletin_templates', 'id',
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment='주보 템플릿 ID',
        existing_nullable=False,
        existing_server_default=sa.text("nextval('seq_bulletin_templates'::regclass)")
    )
    # ### end Alembic commands ###
