"""church code column add

Revision ID: 7a30619dc068
Revises: 431f9d3b05fb
Create Date: 2025-03-13 14:00:36.654679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7a30619dc068'
down_revision: Union[str, None] = '431f9d3b05fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_churches', sa.Column('church_code', sa.String(), nullable=False))
    op.create_index('ix_churches__church_code', 'tb_churches', ['church_code'], unique=True)

    op.drop_index('ix_tb_users_id', 'tb_users')
    op.drop_index('ix_tb_users_email', 'tb_users')
    op.drop_index('ix_tb_churches_id', 'tb_churches')
    op.drop_index('ix_tb_churches_name', 'tb_churches')
    op.drop_index('ix_tb_church_admins_id', 'tb_church_admins')
    op.drop_index('ix_tb_bulletin_templates_id', 'tb_bulletin_templates')
    op.drop_index('ix_tb_bulletins_id', 'tb_bulletins')
    op.drop_index('ix_tb_bulletins_date', 'tb_bulletins')

    op.create_index('ix_users__id', 'tb_users', ['id'])
    op.create_index('ix_users__email', 'tb_users', ['email'])
    op.create_index('ix_churches__id', 'tb_churches', ['id'])
    op.create_index('ix_churches__name', 'tb_churches', ['name'])
    op.create_index('ix_church_admins__id', 'tb_church_admins', ['id'])
    op.create_index('ix_bulletin_templates__id', 'tb_bulletin_templates', ['id'])
    op.create_index('ix_bulletins__id', 'tb_bulletins', ['id'])
    op.create_index('ix_bulletins__date', 'tb_bulletins', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_churches__church_code', table_name='tb_churches')
    op.drop_column('tb_churches', 'church_code')

    op.drop_index('ix_users__id', 'tb_users')
    op.drop_index('ix_users__email', 'tb_users')
    op.drop_index('ix_churches__id', 'tb_churches')
    op.drop_index('ix_churches__name', 'tb_churches')
    op.drop_index('ix_church_admins__id', 'tb_church_admins')
    op.drop_index('ix_bulletin_templates__id', 'tb_bulletin_templates')
    op.drop_index('ix_bulletins__id', 'tb_bulletins')
    op.drop_index('ix_bulletins__date', 'tb_bulletins')

    op.create_index('ix_tb_users_id', 'tb_users', ['id'])
    op.create_index('ix_tb_users_email', 'tb_users', ['email'])
    op.create_index('ix_tb_churches_id', 'tb_churches', ['id'])
    op.create_index('ix_tb_churches_name', 'tb_churches', ['name'])
    op.create_index('ix_tb_church_admins_id', 'tb_church_admins', ['id'])
    op.create_index('ix_tb_bulletin_templates_id', 'tb_bulletin_templates', ['id'])
    op.create_index('ix_tb_bulletins_id', 'tb_bulletins', ['id'])
    op.create_index('ix_tb_bulletins_date', 'tb_bulletins', ['date'])
    # ### end Alembic commands ###
