"""is_deleted change type and is_published column add

Revision ID: be0f11e70ec5
Revises: 7a30619dc068
Create Date: 2025-03-16 00:59:56.739460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0f11e70ec5'
down_revision: Union[str, None] = '7a30619dc068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_bulletin_templates', 'is_deleted', existing_type=sa.BOOLEAN(), type_=sa.CHAR(length=1), existing_nullable=False, server_default="F")
    op.add_column('tb_bulletins', sa.Column('is_published', sa.CHAR(length=1), nullable=False, server_default="F"))
    op.alter_column('tb_bulletins', 'is_deleted', existing_type=sa.BOOLEAN(), type_=sa.CHAR(length=1), existing_nullable=False, server_default="F")
    op.alter_column('tb_church_admins', 'is_deleted', existing_type=sa.BOOLEAN(), type_=sa.CHAR(length=1), existing_nullable=False, server_default="F")
    op.alter_column('tb_churches', 'is_deleted', existing_type=sa.BOOLEAN(), type_=sa.CHAR(length=1), existing_nullable=False, server_default="F")
    op.alter_column('tb_users', 'is_deleted', existing_type=sa.BOOLEAN(), type_=sa.CHAR(length=1), existing_nullable=False, server_default="F")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'is_deleted', existing_type=sa.CHAR(length=1), type_=sa.BOOLEAN(), existing_nullable=False, server_default=False)
    op.alter_column('tb_churches', 'is_deleted', existing_type=sa.CHAR(length=1), type_=sa.BOOLEAN(), existing_nullable=False, server_default=False)
    op.alter_column('tb_church_admins', 'is_deleted', existing_type=sa.CHAR(length=1), type_=sa.BOOLEAN(), existing_nullable=False, server_default=False)
    op.alter_column('tb_bulletins', 'is_deleted', existing_type=sa.CHAR(length=1), type_=sa.BOOLEAN(), existing_nullable=False, server_default=False)
    op.drop_column('tb_bulletins', 'is_published')
    op.alter_column('tb_bulletin_templates', 'is_deleted', existing_type=sa.CHAR(length=1), type_=sa.BOOLEAN(), existing_nullable=False, server_default=False)
    # ### end Alembic commands ###
