"""add year and month

Revision ID: eb64c1930712
Revises: 594b635e7881
Create Date: 2025-03-18 14:31:20.855010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb64c1930712'
down_revision: Union[str, None] = '594b635e7881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_bulletins', sa.Column('year', sa.Integer(), nullable=True, comment='주보 연도'))
    op.add_column('tb_bulletins', sa.Column('month', sa.Integer(), nullable=True, comment='주보 월'))
    op.create_index('ix_bulletins__concatenated0', 'tb_bulletins', ['year', 'month'], unique=False)
    op.create_index('ix_bulletins__year', 'tb_bulletins', ['year'], unique=False)

    op.execute("UPDATE tb_bulletins SET year = EXTRACT(YEAR FROM date), month = EXTRACT(MONTH FROM date)")
    op.alter_column('tb_bulletins', 'year', nullable=False)
    op.alter_column('tb_bulletins', 'month', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bulletins__year', table_name='tb_bulletins')
    op.drop_index('ix_bulletins__concatenated0', table_name='tb_bulletins')
    op.drop_column('tb_bulletins', 'month')
    op.drop_column('tb_bulletins', 'year')
    # ### end Alembic commands ###
